name: Lint
permissions:
  contents: read
on:
  push:
    branches: [main, next]
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  unused_deps:
    name: Check for unused dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: machete
        uses: bnjbvr/cargo-machete@main

  typos:
    name: Spellcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: typos@1.42.0
      - run: make typos-check

  toml:
    name: Toml formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.10.0
      - run: make toml-check

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with nightly clippy
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add clippy
      - name: make - clippy
        run: make clippy

  format:
    name: Format check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust with rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - name: make - format-check
        run: make format-check

  rustdocs:
    name: Build rust documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update --no-self-update
      - name: make - doc
        run: make doc
